# Generated by Django 5.2.16 on 2026-08-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='From Grassroots to Community Pillar', max_length=255)),
                ('content_paragraph1', models.TextField(blank=True)),
                ('content_paragraph2', models.TextField(blank=True)),
                ('content_paragraph3', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('stat1_value', models.CharField(default='10+', max_length=20)),
                ('stat1_label', models.CharField(default='Years Active', max_length=50)),
                ('stat2_value', models.CharField(default='9,850+', max_length=20)),
                ('stat2_label', models.CharField(default='Lives Impacted', max_length=50)),
                ('stat3_value', models.CharField(default='45', max_length=20)),
                ('stat3_label', models.CharField(default='Clinics Supported', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '📖 About Story',
            },
        ),
        migrations.CreateModel(
            name='DonationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. M-Pesa', max_length=200)),
                ('icon', models.CharField(default='📱', max_length=10)),
                ('details', models.JSONField(blank=True, default=list, help_text='List of detail strings')),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DonationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(help_text='e.g. KSh 500', max_length=50)),
                ('label', models.CharField(help_text='e.g. Supporter', max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Heart', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Heart', max_length=50)),
                ('color', models.CharField(default='bg-primary', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Heart', max_length=50)),
                ('color', models.CharField(default='bg-primary', help_text='CSS bg class', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('link_path', models.CharField(default='/programs', help_text='e.g. /programs', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('progress_pct', models.IntegerField(default=0, help_text='0-100')),
                ('color', models.CharField(default='bg-primary', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('beneficiaries', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 9,850+', max_length=50)),
                ('label', models.CharField(help_text='e.g. Individuals Reached', max_length=100)),
                ('icon', models.CharField(default='Users', help_text='Lucide icon name', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('location', models.CharField(default='Kanduyi', max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(default='Kanduyi', max_length=200)),
                ('stars', models.IntegerField(default=5)),
                ('published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g. 2016', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Shield', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vision', 'Vision'), ('mission', 'Mission')], max_length=10, unique=True)),
                ('statement', models.TextField()),
                ('icon', models.CharField(default='Eye', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '🔭 Vision & Mission',
            },
        ),
        migrations.CreateModel(
            name='VolunteerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Heart', max_length=50)),
                ('color', models.CharField(default='bg-accent', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name_plural': '⚙️ Site Settings'},
        ),
        migrations.AlterField(
            model_name='event',
            name='accent_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='span_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='tag_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='stat_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
