# Generated by Django 5.2.16 on 2026-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_aboutstory_donationmethod_donationtier_focusarea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutstory',
            options={'verbose_name_plural': '📖 About — Story Section'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '📬 Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='donationmethod',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '💰 Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='donationtier',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '💰 Donation Tiers'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date'], 'verbose_name_plural': '📅 Upcoming Events'},
        ),
        migrations.AlterModelOptions(
            name='focusarea',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '📖 About — Focus Areas'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': '🖼️ Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='homehighlight',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '🏠 Highlight Cards'},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_at'], 'verbose_name': 'News Article', 'verbose_name_plural': '📰 News & Blog Articles'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': '🤝 Partners & Donors List'},
        ),
        migrations.AlterModelOptions(
            name='partnerstrip',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '🤝 Partner Name Strip'},
        ),
        migrations.AlterModelOptions(
            name='pastevent',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '📅 Past Event Photos'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['sort_order', 'title'], 'verbose_name_plural': '📋 Programs List'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '🌟 Projects & Impact'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '🏠 Stat Cards'},
        ),
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '🌟 Success Stories'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '🏠 Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='timelinemilestone',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '📖 About — Timeline'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '📖 About — Core Values'},
        ),
        migrations.AlterModelOptions(
            name='visionmission',
            options={'verbose_name_plural': '📖 About — Vision & Mission'},
        ),
        migrations.AlterModelOptions(
            name='volunteerbenefit',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '🙋 Volunteer Benefits'},
        ),
        migrations.AlterModelOptions(
            name='volunteerrole',
            options={'ordering': ['sort_order'], 'verbose_name_plural': '🙋 Volunteer Roles'},
        ),
        migrations.AlterField(
            model_name='donationmethod',
            name='details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='donationmethod',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='donationtier',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donationtier',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homehighlight',
            name='color',
            field=models.CharField(default='bg-primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='homehighlight',
            name='link_path',
            field=models.CharField(default='/programs', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress_pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='icon',
            field=models.CharField(default='Users', max_length=50),
        ),
        migrations.AlterField(
            model_name='timelinemilestone',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
