# Generated by Django 5.2.16 on 2026-08-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_aboutstory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_description', models.TextField(blank=True)),
                ('copyright_text', models.CharField(default='© 2026 Beyond Care Initiative CBO. All rights reserved.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '🔝 Footer Content',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. Facebook, Twitter', max_length=50)),
                ('icon', models.CharField(default='Facebook', help_text='Lucide icon name', max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('location', models.CharField(default='both', help_text='topbar, footer, or both', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '🔝 Social Links',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TopBarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='MapPin', max_length=50)),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '🔝 Top Bar Info',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('path', models.CharField(help_text='e.g. /about or /programs', max_length=200)),
                ('is_cta', models.BooleanField(default=False, help_text='Show as a button')),
                ('cta_style', models.CharField(blank=True, help_text='outline or solid', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cms.navlink')),
            ],
            options={
                'verbose_name_plural': '🔝 Navigation Links',
                'ordering': ['sort_order'],
            },
        ),
    ]
