# Generated by Django 5.2.16 on 2026-08-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_footercontent_sociallink_topbarinfo_navlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='Rethink, Reshape & Restart Our Pathways', max_length=255)),
                ('hero_subtext', models.TextField(default='Beyond Care Initiative CBO is building healthy, empowered, and resilient communities across Bungoma County through health promotion, youth empowerment, and sustainable development.')),
                ('hero_badge', models.CharField(default='Community-Based Organization', max_length=100)),
                ('hero_image', models.ImageField(blank=True, help_text='Upload a background image for the hero section', upload_to='homepage/')),
                ('hero_image_url', models.URLField(blank=True, help_text='Or paste an image URL (used if no upload)', max_length=500)),
                ('cta_primary_text', models.CharField(default='Explore Our Programs', max_length=100)),
                ('cta_primary_link', models.CharField(default='/programs', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Learn About Us', max_length=100)),
                ('cta_secondary_link', models.CharField(default='/about', max_length=200)),
                ('highlights_heading', models.CharField(default='Making a Difference Across Bungoma County', max_length=255)),
                ('highlights_subtext', models.TextField(default='We deliver comprehensive programs that address the most pressing health, social, and economic challenges.')),
                ('testimonials_heading', models.CharField(default='Stories of Transformation', max_length=255)),
                ('volunteer_cta_text', models.CharField(default='Become a Volunteer', max_length=255)),
                ('volunteer_cta_desc', models.TextField(default='Join our team of dedicated volunteers making a real difference.')),
                ('donate_cta_text', models.CharField(default='Support Our Work', max_length=255)),
                ('donate_cta_desc', models.TextField(default='Your donation helps us provide critical health services and youth programs.')),
                ('partners_strip_heading', models.CharField(default='Trusted by Leading Organizations', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '🏠 Home Page Content',
            },
        ),
        migrations.AddField(
            model_name='aboutstory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', upload_to='about/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', upload_to='events/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='homehighlight',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', upload_to='highlights/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', upload_to='news/'),
        ),
        migrations.AddField(
            model_name='pastevent',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', upload_to='pastevents/'),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', upload_to='programs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image', upload_to='stories/'),
        ),
        migrations.AlterField(
            model_name='aboutstory',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL (fallback)', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL (fallback)', max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL (fallback if no upload)', max_length=500),
        ),
        migrations.AlterField(
            model_name='homehighlight',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL (fallback)', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL (fallback)', max_length=500),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL (fallback if no upload)', max_length=500),
        ),
        migrations.AlterField(
            model_name='program',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL (fallback)', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL (fallback)', max_length=500),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL (fallback)', max_length=500),
        ),
    ]
