# Generated by Django 5.2.16 on 2026-08-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_homepage_aboutstory_image_event_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, help_text='Upload logo for header and footer', upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Upload favicon', upload_to='branding/')),
                ('footer_description', models.TextField(blank=True, default='"Rethink, Reshape and Restart Our Pathways." Building healthy, empowered, and resilient communities across Bungoma County through health promotion, youth empowerment, and sustainable development.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '🔝 Site Branding',
            },
        ),
    ]
