# Generated by Django 5.2.16 on 2026-08-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_sitebranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload slide image', upload_to='hero/')),
                ('image_url', models.URLField(blank=True, help_text='Or paste image URL (fallback)', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Slide caption/heading', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Slide description')),
                ('category', models.CharField(blank=True, help_text='e.g. Health, Youth, Community', max_length=100)),
                ('link_path', models.CharField(blank=True, help_text='e.g. /programs or /news', max_length=200)),
                ('link_text', models.CharField(blank=True, default='Learn More', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '🏠 Hero Slides',
                'ordering': ['sort_order'],
            },
        ),
    ]
