# Generated by Django 5.2.16 on 2026-08-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(blank=True, help_text='M-Pesa Daraja Consumer Key', max_length=255)),
                ('consumer_secret', models.CharField(blank=True, help_text='M-Pesa Daraja Consumer Secret', max_length=255)),
                ('passkey', models.CharField(blank=True, help_text='M-Pesa Daraja Passkey', max_length=255)),
                ('shortcode', models.CharField(blank=True, help_text='Paybill or Till number (e.g. 174379)', max_length=50)),
                ('business_name', models.CharField(blank=True, default='Beyond Care Initiative', max_length=200)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '📱 M-Pesa Configuration',
            },
        ),
    ]
