# Generated by Django 5.2.16 on 2026-08-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_mpesaconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('subscribed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '📬 Newsletter Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('username', models.EmailField(blank=True, help_text='SMTP email address', max_length=254)),
                ('password', models.CharField(blank=True, help_text='SMTP password or app password', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(blank=True, help_text='From address for outgoing emails', max_length=254)),
                ('from_name', models.CharField(blank=True, default='Beyond Care Initiative', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '📧 SMTP Configuration',
            },
        ),
    ]
